name = "adnd2nd"
type = "html"

account_id = "b7e8e47c7e17084bd42ae322ab01da55"
workers_dev = true
compatibility_date = "2025-03-25"

[env.production]
workers_dev = false
compatibility_date = "2025-03-25"

[[workers_dev]]
route = "*/index.html"
