name = "adnd2nd"
type = "javascript"

account_id = "gsOH9_rp-mgKwcka6KT4vTal6_aJLwgFxboDrXDO"
workers_dev = true
compatibility_date = "2025-03-25"

[env.production]
workers_dev = false
compatibility_date = "2025-03-25"

[[env.production.r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "adnd2ndpdf"
